"""Initial Neon PostgreSQL Tables

Revision ID: 87a18324a7fc
Revises: 2f6180d1bb82
Create Date: 2026-08-02 15:47:29.287284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87a18324a7fc'
down_revision: Union[str, None] = '2f6180d1bb82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
