"""Add user_id to budgets table for individual budget scope

Revision ID: f1dfd53975c0
Revises: 87a18324a7fc
Create Date: 2026-08-02 22:36:21.419121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1dfd53975c0'
down_revision: Union[str, None] = '87a18324a7fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.create_foreign_key(None, 'budgets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'user_id')
    # ### end Alembic commands ###
